name: dictate
namespace: point808
version: 0.0.1
author: Josh North
display_name: Dictate
description: Set up dictation line
min_wazo_version: 18.02
tags:
  - application
homepage: https://git.point808.com/Point808/wazo-dictate
icon: compress